cvdo: opencv.cpp
	g++ opencv.cpp -o cvdo `pkg-config --cflags opencv4` `pkg-config --libs opencv4`


write: writting.cpp.cpp
	g++ writting.cpp -o write  `pkg-config --cflags opencv4` `pkg-config --libs opencv4` 
